##**Pandas & Numpy**

##**Pandas**

Pandas is a Python library used for data manipulation, analysis, and handling structured datasets.

In [97]:
import pandas as pd

##Load CSV File

In [98]:
df = pd.read_csv("ai_job_dataset.csv")

print(df)

        job_id                    job_title  salary_usd salary_currency  \
0      AI00001        AI Research Scientist       90376             USD   
1      AI00002         AI Software Engineer       61895             USD   
2      AI00003                AI Specialist      152626             USD   
3      AI00004                 NLP Engineer       80215             USD   
4      AI00005                AI Consultant       54624             EUR   
...        ...                          ...         ...             ...   
14995  AI14996            Robotics Engineer       38604             USD   
14996  AI14997  Machine Learning Researcher       57811             GBP   
14997  AI14998                 NLP Engineer      189490             USD   
14998  AI14999                   Head of AI       79461             EUR   
14999  AI15000     Computer Vision Engineer       56481             USD   

      experience_level employment_type company_location company_size  \
0                   SE     

##head()

In [99]:
print(df.head())

    job_id              job_title  salary_usd salary_currency  \
0  AI00001  AI Research Scientist       90376             USD   
1  AI00002   AI Software Engineer       61895             USD   
2  AI00003          AI Specialist      152626             USD   
3  AI00004           NLP Engineer       80215             USD   
4  AI00005          AI Consultant       54624             EUR   

  experience_level employment_type company_location company_size  \
0               SE              CT            China            M   
1               EN              CT           Canada            M   
2               MI              FL      Switzerland            L   
3               SE              FL            India            M   
4               EN              PT           France            S   

  employee_residence  remote_ratio  \
0              China            50   
1            Ireland           100   
2        South Korea             0   
3              India            50   
4         

##tail()

In [100]:
print(df.tail())

        job_id                    job_title  salary_usd salary_currency  \
14995  AI14996            Robotics Engineer       38604             USD   
14996  AI14997  Machine Learning Researcher       57811             GBP   
14997  AI14998                 NLP Engineer      189490             USD   
14998  AI14999                   Head of AI       79461             EUR   
14999  AI15000     Computer Vision Engineer       56481             USD   

      experience_level employment_type company_location company_size  \
14995               EN              FL          Finland            S   
14996               EN              CT   United Kingdom            M   
14997               EX              CT      South Korea            L   
14998               EN              FT      Netherlands            M   
14999               MI              PT          Austria            S   

      employee_residence  remote_ratio  \
14995            Finland            50   
14996     United Kingdom        

##shape

In [101]:
print(df.shape)

(15000, 19)


##info()

In [102]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   job_id                  15000 non-null  object 
 1   job_title               15000 non-null  object 
 2   salary_usd              15000 non-null  int64  
 3   salary_currency         15000 non-null  object 
 4   experience_level        15000 non-null  object 
 5   employment_type         15000 non-null  object 
 6   company_location        15000 non-null  object 
 7   company_size            15000 non-null  object 
 8   employee_residence      15000 non-null  object 
 9   remote_ratio            15000 non-null  int64  
 10  required_skills         15000 non-null  object 
 11  education_required      15000 non-null  object 
 12  years_experience        15000 non-null  int64  
 13  industry                15000 non-null  object 
 14  posting_date            15000 non-null

##describe()

In [103]:
print(df.describe())

          salary_usd  remote_ratio  years_experience  job_description_length  \
count   15000.000000  15000.000000      15000.000000            15000.000000   
mean   115348.965133     49.483333          6.253200             1503.314733   
std     60260.940438     40.812712          5.545768              576.127083   
min     32519.000000      0.000000          0.000000              500.000000   
25%     70179.750000      0.000000          2.000000             1003.750000   
50%     99705.000000     50.000000          5.000000             1512.000000   
75%    146408.500000    100.000000         10.000000             2000.000000   
max    399095.000000    100.000000         19.000000             2499.000000   

       benefits_score  
count    15000.000000  
mean         7.504273  
std          1.450870  
min          5.000000  
25%          6.200000  
50%          7.500000  
75%          8.800000  
max         10.000000  


##columns

In [104]:
print(df.columns)

Index(['job_id', 'job_title', 'salary_usd', 'salary_currency',
       'experience_level', 'employment_type', 'company_location',
       'company_size', 'employee_residence', 'remote_ratio', 'required_skills',
       'education_required', 'years_experience', 'industry', 'posting_date',
       'application_deadline', 'job_description_length', 'benefits_score',
       'company_name'],
      dtype='object')


##dtypes

In [105]:
print(df.dtypes)

job_id                     object
job_title                  object
salary_usd                  int64
salary_currency            object
experience_level           object
employment_type            object
company_location           object
company_size               object
employee_residence         object
remote_ratio                int64
required_skills            object
education_required         object
years_experience            int64
industry                   object
posting_date               object
application_deadline       object
job_description_length      int64
benefits_score            float64
company_name               object
dtype: object


##isnull()

In [106]:
print(df.isnull().sum())

job_id                    0
job_title                 0
salary_usd                0
salary_currency           0
experience_level          0
employment_type           0
company_location          0
company_size              0
employee_residence        0
remote_ratio              0
required_skills           0
education_required        0
years_experience          0
industry                  0
posting_date              0
application_deadline      0
job_description_length    0
benefits_score            0
company_name              0
dtype: int64


##value_counts()

In [107]:
print(df["job_title"].value_counts())

job_title
Machine Learning Researcher    808
AI Software Engineer           784
Autonomous Systems Engineer    777
Machine Learning Engineer      772
AI Architect                   771
Head of AI                     765
NLP Engineer                   762
Robotics Engineer              759
Data Analyst                   759
AI Research Scientist          756
Data Engineer                  749
AI Product Manager             743
Research Scientist             742
Principal Data Scientist       734
AI Specialist                  728
ML Ops Engineer                725
Computer Vision Engineer       724
Data Scientist                 720
Deep Learning Engineer         718
AI Consultant                  704
Name: count, dtype: int64


##unique()

In [108]:
print(df["experience_level"].unique())

['SE' 'EN' 'MI' 'EX']


##nunique()

In [109]:
print(df.nunique())

job_id                    15000
job_title                    20
salary_usd                14315
salary_currency               3
experience_level              4
employment_type               4
company_location             20
company_size                  3
employee_residence           20
remote_ratio                  3
required_skills           13663
education_required            4
years_experience             20
industry                     15
posting_date                486
application_deadline        543
job_description_length     2000
benefits_score               51
company_name                 16
dtype: int64


##sort_values()

In [110]:
print(df.sort_values(by="salary_usd", ascending=False))

        job_id                    job_title  salary_usd salary_currency  \
9891   AI09892  Machine Learning Researcher      399095             USD   
2309   AI02310                 AI Architect      398084             USD   
12499  AI12500        AI Research Scientist      394917             USD   
12803  AI12804                AI Specialist      390292             USD   
317    AI00318               Data Scientist      388754             USD   
...        ...                          ...         ...             ...   
10485  AI10486            Robotics Engineer       32692             USD   
8828   AI08829                 Data Analyst       32666             USD   
343    AI00344                 NLP Engineer       32587             USD   
5974   AI05975                 Data Analyst       32542             USD   
9549   AI09550     Computer Vision Engineer       32519             USD   

      experience_level employment_type company_location company_size  \
9891                EX     

##groupby()

In [111]:
print(df.groupby("experience_level")["salary_usd"].mean())

experience_level
EN     63133.377084
EX    187723.647340
MI     87955.471833
SE    122187.657845
Name: salary_usd, dtype: float64


##sample()

In [112]:
print(df.sample(10))

        job_id                 job_title  salary_usd salary_currency  \
724    AI00725                Head of AI      163009             USD   
13880  AI13881             AI Specialist       69769             EUR   
6535   AI06536             Data Engineer      146336             GBP   
4406   AI04407              NLP Engineer       62881             USD   
6619   AI06620        AI Product Manager       84792             EUR   
13759  AI13760  Computer Vision Engineer      208483             EUR   
1019   AI01020              Data Analyst      108128             USD   
13176  AI13177     AI Research Scientist      136513             GBP   
10420  AI10421      AI Software Engineer      188721             USD   
7091   AI07092      AI Software Engineer       63841             USD   

      experience_level employment_type company_location company_size  \
724                 SE              PT           Sweden            L   
13880               MI              CT           France        

##loc[]

In [113]:
print(df.loc[0:9])

    job_id                 job_title  salary_usd salary_currency  \
0  AI00001     AI Research Scientist       90376             USD   
1  AI00002      AI Software Engineer       61895             USD   
2  AI00003             AI Specialist      152626             USD   
3  AI00004              NLP Engineer       80215             USD   
4  AI00005             AI Consultant       54624             EUR   
5  AI00006              AI Architect      123574             EUR   
6  AI00007  Principal Data Scientist       79670             GBP   
7  AI00008              NLP Engineer       70640             EUR   
8  AI00009              Data Analyst      160710             USD   
9  AI00010      AI Software Engineer      102557             USD   

  experience_level employment_type company_location company_size  \
0               SE              CT            China            M   
1               EN              CT           Canada            M   
2               MI              FL      Switzer

##duplicated()

In [114]:
print(df.duplicated().sum())

0


##drop_duplicates()

In [115]:
df = df.drop_duplicates()

print(df.shape)

(15000, 19)


##mean()

In [116]:
print(df["salary_usd"].mean())

115348.96513333333


##print(df["salary_usd"].mean())

In [117]:
print(df.filter(["job_title","salary_usd","company_name"]))

                         job_title  salary_usd       company_name
0            AI Research Scientist       90376    Smart Analytics
1             AI Software Engineer       61895       TechCorp Inc
2                    AI Specialist      152626    Autonomous Tech
3                     NLP Engineer       80215     Future Systems
4                    AI Consultant       54624  Advanced Robotics
...                            ...         ...                ...
14995            Robotics Engineer       38604  Advanced Robotics
14996  Machine Learning Researcher       57811    Smart Analytics
14997                 NLP Engineer      189490     AI Innovations
14998                   Head of AI       79461    Smart Analytics
14999     Computer Vision Engineer       56481     AI Innovations

[15000 rows x 3 columns]


##query()

In [118]:
print(df.query("salary_usd > 150000"))

        job_id                    job_title  salary_usd salary_currency  \
2      AI00003                AI Specialist      152626             USD   
8      AI00009                 Data Analyst      160710             USD   
14     AI00015        AI Research Scientist      150122             USD   
17     AI00018    Machine Learning Engineer      181139             EUR   
18     AI00019                Data Engineer      155300             USD   
...        ...                          ...         ...             ...   
14976  AI14977                AI Consultant      164620             USD   
14977  AI14978           Research Scientist      325968             USD   
14983  AI14984                 AI Architect      288661             USD   
14992  AI14993  Autonomous Systems Engineer      200047             USD   
14997  AI14998                 NLP Engineer      189490             USD   

      experience_level employment_type company_location company_size  \
2                   MI     

##**Numpy**

NumPy (Numerical Python) is a Python library used for fast numerical computations and working with multidimensional arrays.

In [119]:
import numpy as np

##Create a Multidimensional Array

In [120]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


##Access Values Using Index Numbers

In [121]:
print("Element at (0,1):", arr[0,1])

print("Element at (2,2):", arr[2,2])

print("Element at (1,0):", arr[1,0])

Element at (0,1): 20
Element at (2,2): 90
Element at (1,0): 40


##Mathematical Operations

In [122]:
print("Addition:")
print(arr + 10)

print("\nSubtraction:")
print(arr - 5)

print("\nMultiplication:")
print(arr * 2)

print("\nDivision:")
print(arr / 10)

Addition:
[[ 20  30  40]
 [ 50  60  70]
 [ 80  90 100]]

Subtraction:
[[ 5 15 25]
 [35 45 55]
 [65 75 85]]

Multiplication:
[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]

Division:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


###shape

In [123]:
print(arr.shape)

(3, 3)


###ndim

In [124]:
print(arr.ndim)

2


###size

In [125]:
print(arr.size)

9


###dtype

In [126]:
print(arr.dtype)

int64


###reshape()

In [127]:
print(arr.reshape(1,9))

[[10 20 30 40 50 60 70 80 90]]


###flatten()

In [128]:
print(arr.flatten())

[10 20 30 40 50 60 70 80 90]


###transpose()

In [129]:
print(arr.transpose())

[[10 40 70]
 [20 50 80]
 [30 60 90]]


###max()

In [130]:
print(arr.max())

90


###min()

In [131]:
print(arr.min())

10


###sum()

In [132]:
print(arr.sum())

450


###mean()

In [133]:
print(arr.mean())

50.0


###std()

In [134]:
print(arr.std())

25.81988897471611


###sort()

In [135]:
print(np.sort(arr))

[[10 20 30]
 [40 50 60]
 [70 80 90]]


###unique()

In [136]:
print(np.unique(arr))

[10 20 30 40 50 60 70 80 90]


###concatenate()

In [137]:
arr2 = np.array([[100,110,120]])

print(np.concatenate((arr, arr2), axis=0))

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


###arange()

In [138]:
print(np.arange(1,21))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


###sqrt()

In [139]:
print(np.sqrt(arr))

[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]
 [8.36660027 8.94427191 9.48683298]]


###random.randint()

In [140]:
print(np.random.randint(1,100,(3,3)))

[[18 89 29]
 [60 42 46]
 [12 19  8]]
